apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    app: fx
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: fx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fx-deployment
  labels:
    app: fx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fx
  template:
    metadata:
      labels:
        app: fx
    spec:
      containers:
      - name: flutter
        image: flutter_app
        ports:
        - containerPort: 80
      - name: api
        image: cpp_api
        ports:
        - containerPort: 8081
        env:
          - name: DB_HOST
            value: "db"
          - name: JWT_SECRET
            value: "secret_jwt"

