apiVersion: v1
kind: Pod
metadata:
  name: flutter
spec:
  containers:
    - name: flutter
      image: flutter_app
      ports:
        - containerPort: 80
          hostPort: 8088
---
apiVersion: v1
kind: Pod
metadata:
  name: cpp-api
spec:
  containers:
    - name: api
      image: cpp_api
      ports:
        - containerPort: 8081
      env:
        - name: DB_HOST
          value: "db"
        - name: JWT_SECRET
          value: "secret_jwt"
---
apiVersion: v1
kind: Pod
metadata:
  name: db
spec:
  containers:
    - name: db
      image: docker.io/library/postgres:18.4-alpine3.23
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "admin"
        - name: POSTGRES_DB
          value: "restapi"
      volumeMounts:
        - name: script-file
          mountPath: /docker-entrypoint-initdb.d
        - name: postgresql-dir
          mountPath: /var/lib/postgresql
  volumes:
    - name: script-file
      configMap:
        name: postgres-init
    - name: postgresql-dir
      hostPath:
        path:  ./cpp_api/database/data
        type: DirectoryOrCreate
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  script.sql: |
    CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    pseudo VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL
    );

    -- Then create the 'options' table with a foreign key referencing users(id)
    CREATE TABLE options (
        id SERIAL PRIMARY KEY,
        type VARCHAR(20) NOT NULL,  -- e.g., "Call" or "Put"
        spot DOUBLE PRECISION NOT NULL,
        strike DOUBLE PRECISION NOT NULL,
        rate_domestic DOUBLE PRECISION NOT NULL,
        rate_foreign DOUBLE PRECISION NOT NULL,
        volatility DOUBLE PRECISION NOT NULL,
        maturity DATE NOT NULL,
        day_counter VARCHAR(20) NOT NULL,  -- e.g., "Actual360", "Actual365", etc.
        price DOUBLE PRECISION NOT NULL,
        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
    );

