class Rates {
  final double AUD; // "Australian Dollar",
  final double BGN; // "Bulgarian Lev",
  final double BRL; // "Brazilian Real",
  final double CAD; // "Canadian Dollar",
  final double CHF; // "Swiss Franc",
  final double CNY; // "Chinese Renminbi Yuan",
  final double CZK; // "Czech Koruna",
  final double DKK; // "Danish Krone",
  final double EUR; // "Euro",
  final double GBP; // "British Pound",
  final double HKD; // "Hong Kong Dollar",
  final double HUF; // "Hungarian Forint",
  final double IDR; // "Indonesian Rupiah",
  final double ILS; // "Israeli New Sheqel",
  final double INR; // "Indian Rupee",
  final double ISK; // "Icelandic Króna",
  final double JPY; // "Japanese Yen",
  final double KRW; // "South Korean Won",
  final double MXN; // "Mexican Peso",
  final double MYR; // "Malaysian Ringgit",
  final double NOK; // "Norwegian Krone",
  final double NZD; // "New Zealand Dollar",
  final double PHP; // "Philippine Peso",
  final double PLN; // "Polish Złoty",
  final double RON; // "Romanian Leu",
  final double SEK; // "Swedish Krona",
  final double SGD; // "Singapore Dollar",
  final double THB; // "Thai Baht",
  final double TRY; // "Turkish Lira",
  final double USD; // "United States Dollar",
  final double ZAR;

  Rates({
    required this.AUD,
    required this.BGN,
    required this.BRL,
    required this.CAD,
    required this.CHF,
    required this.CNY,
    required this.CZK,
    required this.DKK,
    required this.EUR,
    required this.GBP,
    required this.HKD,
    required this.HUF,
    required this.IDR,
    required this.ILS,
    required this.INR,
    required this.ISK,
    required this.JPY,
    required this.KRW,
    required this.MXN,
    required this.MYR,
    required this.NOK,
    required this.NZD,
    required this.PHP,
    required this.PLN,
    required this.RON,
    required this.SEK,
    required this.SGD,
    required this.THB,
    required this.TRY,
    required this.USD,
    required this.ZAR,
  });

  Rates.empty()
      : AUD = 0,
        BGN = 0,
        BRL = 0,
        CAD = 0,
        CHF = 0,
        CNY = 0,
        CZK = 0,
        DKK = 0,
        EUR = 0,
        GBP = 0,
        HKD = 0,
        HUF = 0,
        IDR = 0,
        ILS = 0,
        INR = 0,
        ISK = 0,
        JPY = 0,
        KRW = 0,
        MXN = 0,
        MYR = 0,
        NOK = 0,
        NZD = 0,
        PHP = 0,
        PLN = 0,
        RON = 0,
        SEK = 0,
        SGD = 0,
        THB = 0,
        TRY = 0,
        USD = 0,
        ZAR = 0;

  Map<String, double> toMap() {
    return {
      'AUD': AUD,
      'BGN': BGN,
      'BRL': BRL,
      'CAD': CAD,
      'CHF': CHF,
      'CNY': CNY,
      'CZK': CZK,
      'DKK': DKK,
      'EUR': EUR,
      'GBP': GBP,
      'HKD': HKD,
      'HUF': HUF,
      'IDR': IDR,
      'ILS': ILS,
      'INR': INR,
      'ISK': ISK,
      'JPY': JPY,
      'KRW': KRW,
      'MXN': MXN,
      'MYR': MYR,
      'NOK': NOK,
      'NZD': NZD,
      'PHP': PHP,
      'PLN': PLN,
      'RON': RON,
      'SEK': SEK,
      'SGD': SGD,
      'THB': THB,
      'TRY': TRY,
      'USD': USD,
      'ZAR': ZAR,
    };
  }
}
